name: Dhan Volume Tracker

on:
  schedule:
    - cron: '30 3 * * 1-5' # 9:00 AM IST
  workflow_dispatch:      # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests websocket-client pytz python-dotenv

      - name: Run Tracker
        env:
          DHAN_CLIENT_ID: ${{ secrets.DHAN_CLIENT_ID }}
          DHAN_ACCESS_TOKEN: ${{ secrets.DHAN_ACCESS_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SIGNAL_AMOUNT: ${{ secrets.SIGNAL_AMOUNT }}
        run: python nse_data.py
